# Generated by Django 4.1.7 on 2023-03-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='alert',
            field=models.CharField(max_length=15),
        ),
    ]
